export const DISCORD_URL = "https://discord.gg/MUxsQCf587";

export const PHRASES = {
  ru: [
    "Хочешь больше карт? Загляни в наш Дискорд.",
    "Нужна помощь с модулем? Мы всегда на связи в Дискорде.",
    "Новые карты каждую неделю — все анонсы в Дискорде.",
    "Нашёл баг? Расскажи нам в Дискорде.",
    "Присоединяйся к 200+ мастерам подземелий в нашем Дискорде.",
    "Хочешь бета-доступ раньше всех? Мы в Дискорде.",
    "Создано Dungeons Lab.",
    "Живое общение с командой — только в Дискорде.",
    "Есть идея для модуля? Поделись в Дискорде.",
    "Секретные карты Баровии сначала появляются в Дискорде.",
    "Общайся с другими мастерами в нашем Дискорде.",
    "Хочешь узнать, что мы делаем дальше? Загляни в Дискорд.",
    "Наши карты сделаны мастерами для мастеров.",
    "Голосуй за следующий модуль в нашем Дискорде.",
    "Ищешь референсы для своей кампании? У нас их сотни.",
    "Все обновления и релизы — в нашем Дискорде.",
    "Хочешь показать свою кампанию другим? Заходи в шоукейс в Дискорде.",
    "Обновление вышло — подробности в новостях Discord.",
    "Твой отзыв помогает нам стать лучше. Пиши в Дискорде.",
    "Ищешь единомышленников для игры? Начни с нашего Дискорда.",
    "Задай вопрос напрямую разработчику — в Дискорде.",
    "А знаешь ли ты, что такое счастье?",
    "Ты чувствуешь себя одиноко? Переходи в наш Дискорд.",
    "Мы тоже иногда теряем токены. Заходи, поплачем вместе.",
    "99 багов в коде, один пофиксили — осталось 98.",
    "Стратенвакер уже завтра. Пока можешь просто отдохнуть.",
    "Наш GM тоже иногда забывает про модификаторы.",
    "Здесь никто не осудит тебя за критический провал.",
    "Кубик выпал единицей? Мы понимаем твою боль.",
    "Иногда лучший лут — это новые друзья в Дискорде.",
  ],
  en: [
    "Want more maps? Join our Discord.",
    "Stuck on a bug? We're on Discord.",
    "New maps drop weekly — all the news on Discord.",
    "Found a bug? Tell us on Discord.",
    "Join 200+ GMs building worlds in our Discord.",
    "Get early beta access — find us on Discord.",
    "Made with love by Dungeons Lab.",
    "Chat directly with the team on Discord.",
    "Got a feature idea? Tell us on Discord.",
    "Secret Barovia maps drop first on Discord.",
    "Talk shop with fellow GMs in our Discord.",
    "Curious what's next? Come see it on Discord.",
    "Our maps are made by GMs, for GMs.",
    "Vote on the next module in our Discord.",
    "Need references for your campaign? We've got hundreds.",
    "Every update and release lands on Discord first.",
    "Show off your campaign in our showcase channel.",
    "New update just dropped — details on Discord.",
    "Your feedback shapes what we build. Tell us on Discord.",
    "Looking for a group? Start in our Discord.",
    "Ask the dev your questions directly on Discord.",
    "Feeling lonely? So is your party. Join our Discord.",
    "We also fumble initiative sometimes. Come commiserate.",
    "99 bugs in the code, fixed one, 98 left.",
    "Strahd's coming tomorrow. Relax while you still can.",
    "Our GM forgets modifiers too, don't worry.",
    "Nobody judges a critical fail in here.",
    "Rolled a nat 1? Discord won't judge you.",
    "Sometimes the best loot is just new friends.",
    "Even liches need a coffee break sometimes.",
  ],
};

export function randomPhrase(lang) {
  const list = PHRASES[lang] ?? PHRASES.en;
  return list[Math.floor(Math.random() * list.length)];
}
